### ISSUE TITLE
Unable to use $ref in OAS Path Item objects

### ISSUE THREAD

**Issue by ncovercash** [aml-org/amf#1338]
### **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question
- [ ] other

### **What is the current behavior?**

Currently, `$ref` is improperly resolved for relative paths within Path Item objects _that, themselves, are $ref'd_ within API schemas.

### **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

> _The extent of AMF being used is, effectively, just `amf.OASConfiguration.OAS30().baseUnitClient().parseDocument("file://foo.yaml")`._

#### _Since this is a schema issue, I created a minimal repo showing the bug:_

Using the [OAS 3.0 petstore example](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml), the parsing engine breaks if a path (such as /pet) is loaded from a `$ref` which itself contains `$ref`s (to schemas or otherwise).  An error is reported that the reference is unresolved.

When testing with this, the only way I have found to make it pass is prefixing `/` on all relative references, however, this does not work in all contexts (and fails with the [`swagger-cli` tool](https://www.npmjs.com/package/swagger-cli) for validation).

I have made https://github.com/ncovercash/amf-ref-demo with a full demo/MVE of this issue, with the `main.js` running `.parseDocument` and `.validate`.

The `combined-petstore` is a working example with only schemas separated from the main specification file.

The `separate-petstore` separates a Path Item from the main file (the /pets) endpoint into `paths/pets.yaml` -- this is valid per [the spec](https://swagger.io/specification/#path-item-object).  However, on this, `.parseDocument` fails, reporting that the references in `pets.yaml` is unresolved.

The `separate-petstore-base-refs` is the same as the above, however, `/` is prefixed to the refs in the Path Item object.  This fixes the issue with the parsing/validation, however, this fails validation against the actual spec (since `/` may not be the parent directory).

### **What is the expected behavior?**

The `separate-petstore` example, from above, would parse and validate correctly.

### **What is the motivation/use case for changing the behavior? (for feature requests)**

N/A

### **Please tell us about your environment:**
  
  - AMF Version: 5.0.5
  - AMF Distribution: JS 
  - Operating System: Ubuntu 20.04
  - Link to your project: https://github.com/ncovercash/amf-ref-demo

### **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

I think something's being incorrectly resolved with the path here -- not sure what else I can contribute, however.  Dereferencing the schema with the separate path item then passes validation with AMF, so I'm fairly certain the issue is with how these references are handled internally (although it's strange I've only found this with Path Items, not Schemas or anything else).

I saw some stuff about `$ref`s being handled incorrectly, however, none seemed to match this issue (and they are all fixes).

**Comment by arielmirra** [comment]
Hi @ncovercash! This is a bug, I reported it internally and will keep you updated when I investigate further. Thanks for such a clear report!

internal link just for history sake: https://gus.my.salesforce.com/a07EE00000sRUzYYAW

**Comment by hghianni** [comment]
Hello @ncovercash  this issue has been fixed and will be present in the next AMF release version 5.0.7, probably May 4. Thank you!

**Comment by ncovercash** [comment]
@hghianni @arielmirra  thank you for addressing this issue!  It looks like this fixed all of the test cases I provided previously (separate paths and schemas), however the same bug is still present for parameters.

I updated https://github.com/ncovercash/amf-ref-demo with this example as before: [diff](https://github.com/ncovercash/amf-ref-demo/commit/baf0bc56a78da492389b4ca896eecc22fb69612b).

The same validation code used as before is now providing the following result:

```
Parsing file:///Users/ncovercash/amf-ref-demo/separate-petstore/petstore.yaml
parsingResult.conforms: false
parsingResult.results.length: 2
Violation: 'name' property is required in a parameter.
Violation: Cannot find parameter or payload reference ../parameters/limit.yaml
Model: file:///Users/ncovercash/amf-ref-demo/separate-petstore/petstore.yaml
Conforms: false
Number of results: 2

Level: Violation

- Constraint: http://a.ml/vocabularies/amf/parser#parameter-name-required
  Message: 'name' property is required in a parameter.
  Severity: Violation
  Target: file:///Users/ncovercash/amf-ref-demo/separate-petstore/petstore.yaml#/web-api/endpoint/%2Fpets/supportedOperation/get/listPets/expects/request/parameter/parameter/default-binding/parameter_1
  Property: 
  Range: [(7,6)-(8,0)]
  Location: file:///Users/ncovercash/amf-ref-demo/separate-petstore/paths/pets.yaml

- Constraint: http://a.ml/vocabularies/amf/parser#unresolved-parameter
  Message: Cannot find parameter or payload reference ../parameters/limit.yaml
  Severity: Violation
  Target: file:///Users/ncovercash/amf-ref-demo/separate-petstore/petstore.yaml#/web-api/endpoint/%2Fpets/supportedOperation/get/listPets/expects/request/parameter/parameter/default-binding/parameter_1
  Property: 
  Range: [(7,6)-(8,0)]
  Location: file:///Users/ncovercash/amf-ref-demo/separate-petstore/paths/pets.yaml

--------
Validating
validationResult.conforms: false
validationResult.results.length: 1
Violation: 'in' property of a Parameter object is mandatory
ModelId: file:///Users/ncovercash/amf-ref-demo/separate-petstore/petstore.yaml
Profile: OAS 3.0
Conforms: false
Number of results: 1

Level: Violation

- Constraint: http://a.ml/vocabularies/amf/parser#Parameter-binding-minCount
  Message: 'in' property of a Parameter object is mandatory
  Severity: Violation
  Target: http://amferror.com/#errorParameter/file://Users/ncovercash/amf-ref-demo/separate-petstore/petstore.yaml#/web-api/endpoint/%2Fpets/supportedOperation/get/listPets/expects/request/parameter/parameter/default-binding/parameter_1/parameter/default-binding/default-name
  Property: http://a.ml/vocabularies/apiContract#binding
  Range: [(7,6)-(8,0)]
  Location: file:///Users/ncovercash/amf-ref-demo/separate-petstore/paths/pets.yaml
```

Per the spec, this should also be permissible (it validates fine with `swagger-cli`).

If you would like me to create a new issue instead of re-opening this one, let me know and I'd be happy to do that!

**Comment by hghianni** [comment]
Hi @ncovercash, I'm glad this fixes the previous issue. Please create a new issue, so I can report it internally only for this case. I fixed several related cases but this is handled differently that's why I wasn't able to detect it. Thank you!
